### ISSUE TITLE
NPE when creating nodes

### ISSUE THREAD

**Issue by zumlcn** [Azure/cyclecloud-lsf#30]
```
$ cyclecloud -v
CycleCloud 7.9.6-1280

$ uname -a
Linux cyclecloud 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

LSF version: 10.1.0.9 (SPK9)

When creating a node from LSF, the cyclecloud throws NPE immediately:

```
2020-07-12 14:15:54,177 INFO [com.cyclecomputing.web.RequestHandler request-1367] - **BEGIN POST request to /clusters/lsf-cluster/nodes/create
2020-07-12 14:15:54,371 INFO [com.cyclecomputing.appsupport.action.ActionExecutor request-1367] - Running action Add:Cloud.Node...
2020-07-12 14:15:54,379 ERROR [com.cyclecomputing.grid.common.plugin.PluginServlet request-1367] - Error while processing request
java.lang.NullPointerException
        at com.cyclecomputing.cloud.node.CachedQuotaTracker$CachedReservation.getRegionCache(CachedQuotaTracker.java:422)
        at com.cyclecomputing.cloud.node.CachedQuotaTracker$CachedReservation.getEffectiveQuota(CachedQuotaTracker.java:429)
        at com.cyclecomputing.cloud.node.CachedQuotaTracker$CachedReservation.getAvailableCount(CachedQuotaTracker.java:347)
        at com.cyclecomputing.cloud.nodearray.NodeCreator$SetValidator.validateSet(NodeCreator.java:410)
        at com.cyclecomputing.cloud.nodearray.NodeCreator.createNodes(NodeCreator.java:189)
        at com.cyclecomputing.cloud.node.NodeArrayController.createNodes(NodeArrayController.java:91)
        at com.cyclecomputing.cloud.node.rest.CreateNodesPlugin.execute(CreateNodesPlugin.java:371)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cyclecomputing.apex.plugin.java.JavaPluginFunction.call(JavaPluginFunction.java:157)
        at com.cyclecomputing.apex.plugin.PluginUtilities.call(PluginUtilities.java:151)
        at com.cyclecomputing.apex.plugin.PluginBase.call(PluginBase.java:96)
        at com.cyclecomputing.appsupport.action.ActionExecutor.runAction(ActionExecutor.java:245)
        at com.cyclecomputing.appsupport.restlet.action.ActionHandlerProvider$CustomHandler.execute(ActionHandlerProvider.java:205)
        at com.cyclecomputing.appsupport.restlet.action.ActionHandlerProvider$CustomHandler.acceptRepresentation(ActionHandlerProvider.java:139)
        at org.restlet.resource.Resource.post(Resource.java:683)
        at org.restlet.resource.Resource.handlePost(Resource.java:537)
        at com.cyclecomputing.apex.rest.plugin.FilteredHandler.handleInternal(FilteredHandler.java:119)
        at com.cyclecomputing.apex.rest.plugin.FilteredHandler.access$000(FilteredHandler.java:22)
        at com.cyclecomputing.apex.rest.plugin.FilteredHandler$1.run(FilteredHandler.java:80)
        at com.cyclecomputing.apex.rest.plugin.FilteredHandler.handle(FilteredHandler.java:90)
        at com.cyclecomputing.apex.rest.plugin.FilteredHandler.handlePost(FilteredHandler.java:63)
        at org.restlet.Finder.handle(Finder.java:357)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Router.handle(Router.java:504)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at com.noelios.restlet.StatusFilter.doHandle(StatusFilter.java:130)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at com.noelios.restlet.ChainHelper.handle(ChainHelper.java:124)
        at com.noelios.restlet.application.ApplicationHelper.handle(ApplicationHelper.java:112)
        at org.restlet.Application.handle(Application.java:341)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Router.handle(Router.java:504)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at org.restlet.Router.handle(Router.java:504)
        at org.restlet.Filter.doHandle(Filter.java:150)
        at org.restlet.Filter.handle(Filter.java:195)
        at com.noelios.restlet.ChainHelper.handle(ChainHelper.java:124)
        at org.restlet.Component.handle(Component.java:673)
        at org.restlet.Server.handle(Server.java:331)
        at com.noelios.restlet.ServerHelper.handle(ServerHelper.java:68)
        at com.noelios.restlet.http.HttpServerHelper.handle(HttpServerHelper.java:147)
        at com.noelios.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:881)
        at com.cyclecomputing.grid.common.plugin.PluginServlet.service(PluginServlet.java:123)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.springframework.web.servlet.handler.SimpleServletHandlerAdapter.handle(SimpleServletHandlerAdapter.java:63)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:857)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:792)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:475)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:440)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.cyclecomputing.web.RequestHandler$CustomRunnable.delegate(RequestHandler.java:155)
        at com.cyclecomputing.web.RequestHandler$CustomRunnable.run(RequestHandler.java:127)
        at com.cyclecomputing.apex.plugin.impl.PluginTaskAdapter$PythonRunnable.run(PluginTaskAdapter.java:37)
        at com.cyclecomputing.apex.ad.auth.impl.ThreadContextTaskAdapter$CustomRunnable.run(ThreadContextTaskAdapter.java:42)
        at com.cyclecomputing.apex.event.impl.EventLogRunnable.run(EventLogRunnable.java:23)
        at com.cyclecomputing.core.concurrency.logging.LoggingRunnable.run(LoggingRunnable.java:31)
        at com.cyclecomputing.web.RequestHandler.doFilter(RequestHandler.java:68)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:138)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:185)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:608)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2020-07-12 14:15:54,380 INFO [com.cyclecomputing.web.RequestHandler request-1367] - **END   POST request to /clusters/lsf-cluster/nodes/create, 500, 0.2 sec
2020-07-12 14:15:57,269 INFO [chef.host_timeout timer-1233] - Deleting Chef hosts that have not been heard from in 86400.000000 seconds
2020-07-12 14:15:57,288 INFO [chef.host_timeout timer-1233] - Finished deleting timed-out chef hosts
```

**Comment by carogonzalezzapata** [comment]
Issue fixed in release 8.1
